// frontend/src/components/Sidebar.tsx
import {FiInstagram, FiMenu} from "solid-icons/fi";
import {createEffect, createSignal, onMount} from "solid-js";
import {gsap} from "gsap";

const Sidebar = () => {
    const [menu, set_menu] = createSignal(false)

    onMount(() => {
        gsap.set(".sidebar", {x: "100%"})
        gsap.set(".backdrop", {opacity: 0, display: "none"})
    })

    createEffect(() => {
        const timeline = gsap.timeline()
        if (menu()) gsap.set(".backdrop", {display: "block"})

        timeline.to(".sidebar", {
            x: menu() ? "0%" : "100%",
            duration: .5,
            ease: "power2.out"
        }, 0)

        timeline.to(".backdrop", {
            opacity: menu() ? 1 : 0,
            duration: .5,
            ease: "power2.out",
            onComplete: () => {
                if (!menu()) gsap.set(".backdrop", {display: "none"})
            }
        }, 0)
    })

    return (
        <>
            <div
                onmouseenter={() => set_menu(true)}
                class="absolute z-10 w-fit h-fit right-4 top-4">
                <button><FiMenu class={"size-8"}/></button>
            </div>

            <div
                onmouseleave={() => set_menu(false)}
                class="sidebar fixed font-[Big_Shoulders] text-right p-4 flex flex-col space-y-4 font-medium text-5xl z-20 w-fit h-screen right-0 bg-white">
                <a href="#">&gt; about us</a>
                <a href="#">&gt; portfolios</a>
                <a href="#">&gt; business inquiry</a>
                <a href="#">&gt; Q + A</a>

                <div class="absolute bottom-4 left-4 text-2xl text-left">
                    <a  class={"flex items-center gap-x-1 text-2xl underline"}
                        href="https://instragram.com/media.vc" target={"_blank"}><FiInstagram/>media.vc</a>
                    <a  class={"flex items-center gap-x-1 text-2xl underline"}
                        href="https://instragram.com/nathanxphoto" target={"_blank"}><FiInstagram/>nathanxphoto</a>
                </div>
            </div>

            <div class="backdrop fixed z-10 backdrop-blur-sm bg-black/40 top-0 left-0 h-screen w-screen"/>
        </>
    )
}

export default Sidebar;

// frontend/src/components/Sidebar.svelte
<script lang="ts">
    import {onDestroy, onMount} from "svelte";
    import Icon from "@iconify/svelte";
    import {gsap} from "gsap";

    let menu_open = $state(false);
    let button: HTMLElement;
    let sidebar: HTMLElement;
    let backdrop: HTMLElement;

    onMount(() => {
        gsap.set(backdrop, {
            display: "none",
            backdropFilter: "blur(0px)",
            opacity: 0
        })
        gsap.set(sidebar, {
            xPercent: 100
        })

        document.addEventListener("click", handle_click_off)

        onDestroy(() => {
            document.removeEventListener("click", handle_click_off)
        })
    })

    $effect(() => {
        if (menu_open) {
            const timeline = gsap.timeline()
            gsap.set(backdrop, {display: "block"})

            timeline.to(sidebar, {
                xPercent: 0,
                duration: .4,
                ease: "power2.out"
            }, 0)
            timeline.to(backdrop, {
                opacity: 1,
                backdropFilter: "blur(10px)",
                duration: .4,
                ease: "power2.out"
            }, 0)
        } else {
            const timeline = gsap.timeline()

            timeline.to(sidebar, {
                xPercent: 100,
                duration: .4,
                ease: "power2.out"
            }, 0)
            timeline.to(backdrop, {
                opacity: 0,
                backdropFilter: "blur(0px)",
                duration: .4,
                ease: "power2.out",
                onComplete: () => {gsap.set(backdrop, {display: "none"})}
            }, .2)
        }
    })

    const handle_click_off = (event: Event) => {
        const target = event.target as Node;

        if (menu_open && !sidebar.contains(target) && !button.contains(target)) {
            menu_open = false;
        }
    }
</script>


<button bind:this={button} class="fixed top-4 right-4 z-30"
        onclick={() => menu_open = !menu_open}
>
    <Icon class="size-12" icon="material-symbols:menu-rounded" />
</button>

<section bind:this={sidebar} class="fixed w-fit h-screen top-0 right-0 p-8 z-20 bg-[#f9f9f9]">
    <ul class="mt-12 text-right text-5xl space-y-6">
        <li><a href="/about">> about us</a></li>
        <li><a href="/portfolios">> portfolios</a></li>
        <li><a href="/business">> business inquiry</a></li>
    </ul>
</section>

<div bind:this={backdrop} class="fixed w-screen h-screen z-10 bg-black/30"></div>
