// frontend/src/components/Sidebar.tsx
import {FiInstagram, FiMenu} from "solid-icons/fi";
import {onMount} from "solid-js";
import marble_texture from "../assets/marble_texture.jpg";
import villaliu from "../assets/villaliu.png";
import {ScrollToPlugin} from "gsap/ScrollToPlugin";
import {gsap} from "gsap";

gsap.registerPlugin(ScrollToPlugin)
const Sidebar = () => {
    onMount(() => {
        gsap.set(".sidebar", {x: "100%"})
        gsap.set(".backdrop", {opacity: 0, display: "none"})
    })

    const show_sidebar = (start: boolean) => {
        const timeline = gsap.timeline()
        if (start) gsap.set(".backdrop", {display: "block"})

        timeline.to(".sidebar", {
            x: start ? "0%" : "100%",
            duration: .5,
            ease: "power2.out"
        }, 0)

        timeline.to(".backdrop", {
            opacity: start ? 1 : 0,
            duration: .5,
            ease: "power2.out",
            onComplete: () => {
                if (!start) gsap.set(".backdrop", {display: "none"})
            }
        }, 0)
    }

    return (
        <>
            <section
                onmouseenter={() => show_sidebar(true)}
                class="fixed z-10 w-fit h-fit right-4 top-4">
                <button><FiMenu class={"size-8"}/></button>
            </section>

            <section
                onmouseleave={() => show_sidebar(false)}
                class="sidebar top-0 right-0 fixed p-4 font-[Big_Shoulders] text-right flex flex-col space-y-4 font-medium text-5xl z-20 w-fit h-screen">
                <a href="/"><img class={"w-[18rem] mx-auto"} src={villaliu} alt="villaliu logo"/></a>
                <button
                    onclick={() => {
                        if (location.pathname === "/") {
                            gsap.to(window, {duration: 1, ease: "sine.inOut", scrollTo: "#aboutus"})
                        } else {
                            location.assign("/#aboutus")
                        }
                    }}
                    class={"hover:underline text-right"}>&gt; about us</button>
                <a href="/portfolios" class={"hover:underline"}>&gt; portfolios</a>
                <a href="#" class={"hover:underline"}>&gt; business inquiry</a>
                <a href="#" class={"hover:underline"}>&gt; Q + A</a>

                <div class="absolute bottom-0 left-4 text-2xl text-left">
                    <a  class={"flex items-center gap-x-1 text-2xl hover:underline"}
                        href="https://instragram.com/media.vc" target={"_blank"}><FiInstagram/>media.vc</a>
                    <a  class={"flex items-center gap-x-1 text-2xl hover:underline"}
                        href="https://instragram.com/nathanxphoto" target={"_blank"}><FiInstagram/>nathanxphoto</a>
                </div>
                <img src={marble_texture} alt="background texture" class={"absolute top-0 left-0 w-full h-full -z-10"}/>
            </section>

            <div class="backdrop fixed z-10 backdrop-blur-sm bg-black/40 top-0 left-0 h-screen w-screen"/>
        </>
    )
}

export default Sidebar;

// frontend/src/lib/Sidebar.svelte
<script lang="ts">
    import {onDestroy, onMount} from "svelte";
    import Icon from "@iconify/svelte";
    import {gsap} from "gsap";
    import {ScrollToPlugin} from "gsap/dist/ScrollToPlugin";
    import {goto} from "$app/navigation";

    let menu_open = $state(false);
    let button: HTMLElement;
    let sidebar: HTMLElement;
    let backdrop: HTMLElement;

    gsap.registerPlugin(ScrollToPlugin)
    onMount(() => {
        gsap.set(backdrop, {
            display: "none",
            backdropFilter: "blur(0px)",
            opacity: 0
        })
        gsap.set(sidebar, {
            xPercent: 100
        })

        document.addEventListener("click", handle_click_off)

        onDestroy(() => {
            document.removeEventListener("click", handle_click_off)
        })
    })

    $effect(() => {
        if (menu_open) {
            const timeline = gsap.timeline()
            gsap.set(backdrop, {display: "block"})

            timeline.to(sidebar, {
                xPercent: 0,
                duration: .4,
                ease: "power2.out"
            }, 0)
            timeline.to(backdrop, {
                opacity: 1,
                backdropFilter: "blur(10px)",
                duration: .4,
                ease: "power2.out"
            }, 0)
        } else {
            const timeline = gsap.timeline()

            timeline.to(sidebar, {
                xPercent: 100,
                duration: .4,
                ease: "power2.out"
            }, 0)
            timeline.to(backdrop, {
                opacity: 0,
                backdropFilter: "blur(0px)",
                duration: .4,
                ease: "power2.out",
                onComplete: () => {gsap.set(backdrop, {display: "none"})}
            }, .2)
        }
    })

    const handle_click_off = (event: Event) => {
        const target = event.target as Node;

        if (menu_open && !sidebar.contains(target) && !button.contains(target)) {
            menu_open = false;
        }
    }

    const about_click = () => {
        if (location.pathname !== "/") {
            goto("/#aboutus")
        } else {
            gsap.to(window, {
                scrollTo: "#aboutus",
                duration: 1,
                ease: "power2.out",
            })
        }
        menu_open = false;
    }

    const home_click = () => {
        if (location.pathname !== "/") {
            goto("/")
        } else {
            gsap.to(window, {
                scrollTo: 0,
                duration: 1,
                ease: "power2.out",
            })
        }
        menu_open = false;
    }
</script>


<button bind:this={button} class="fixed top-4 right-4 z-30 backdrop-blur-xs"
        onclick={() => menu_open = !menu_open}
>
    <Icon class="size-12" icon="material-symbols:menu-rounded" />
</button>

<section bind:this={sidebar} class="fixed w-fit h-screen top-0 right-0 p-8 z-20 bg-[#f9f9f9]">
    <button onclick={home_click}><img class="mt-12 object-cover w-[20vw]" src="/villaliu.png" alt="logo"></button>
    <ul class="mt-4 text-right text-5xl space-y-6">
        <li><button class="hover:underline" onclick={about_click}>> about us</button></li>
        <li><a class="hover:underline" href="/portfolios">> portfolios</a></li>
        <li><a class="hover:underline" href="/business">> business inquiry</a></li>
    </ul>
</section>

<div bind:this={backdrop} class="fixed w-screen h-screen z-10 bg-black/30"></div>
